api_platform:
    title: Sample
    version: 1.0.0
#    formats:
#        json: ['application/json']
#        html: ['text/html']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

doctrine:
    orm:
        filters:
            # user_filterというキーでUserFilterを登録
            user_filter:
                class: App\Filter\UserFilter
